apiVersion: v2
name: speedtest-exporter
description: Prometheus exporter for Ookla Speedtest CLI
type: application
version: 0.0.4
appVersion: "0.0.4"
kubeVersion: ">=1.25.0"
home: https://github.com/darox/speedtest-prometheus-exporter
sources:
  - https://github.com/darox/speedtest-prometheus-exporter
keywords:
  - prometheus
  - exporter
  - speedtest
  - network
maintainers:
  - name: darox
