#!/usr/bin/env bash
set -euo pipefail

echo "Running custom pre-commit hooks..."

docker build --target test -t speedtest-exporter:test .
docker build -t speedtest-exporter .
docker run --rm ghcr.io/aquasecurity/trivy@sha256:be1190afcb28352bfddc4ddeb71470835d16462af68d310f9f4bca710961a41e image --severity CRITICAL,HIGH speedtest-exporter
